# Generated by Django 3.0 on 2019-12-18 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='todo_title',
        ),
    ]
