# Generated by Django 3.0 on 2019-12-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_auto_20191218_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.CharField(max_length=20),
        ),
    ]
